rbac:
  create: true

metrics:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mariadb.nitilon.local."

replication:
  enabled: false

master:
  persistence:
    enabled: true
    storageClass: default

service:
  type: LoadBalancer
